name: Publish to NPM
on:
    release:
        types: [created]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: 18
                registry-url: 'https://registry.npmjs.org'
            - name: Building
              run: make
            - name: Publishing
              working-directory: ./dist
              run: npm publish --access public
              env:
                NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}